---
#System Settings
php_modules: [ 'php-curl', 'php-gd', 'php-mbstring', 'php-xml', 'php-xmlrpc', 'php-soap', 'php-intl', 'php-zip' ]

#MySQL Settings
mysql_root_password: "mysql_root_password"
mysql_db: "wordpress"
mysql_user: "zeus"
mysql_password: 'Very@sercurePasSWord1234!'

#HTTP Settings
#http_host: "localhost"
http_host: "olympe.god"
http_conf: "olympe_wordpress.conf"
http_port: "80"

ad_safe_mode_password: "Pantheon@2024"

