# Dieu grecs
greek_gods:
  - { name: Zeus, img: img_zeus.png, desc: "{{ zeus_desc }}" }
  - { name: Héra, img: img_hera.png, desc: "{{ hera_desc }}" }
  - { name: Poséidon, img: img_poseidon.png, desc: "{{ poseidon_desc }}" }
  - { name: Déméter, img: img_demeter.png, desc: "{{ demeter_desc }}" }
  - { name: Athéna, img: img_athena.png, desc: "{{ athena_desc }}" }
  - { name: Apollon, img: img_apollon.png, desc: "{{ apollon_desc }}" }
  - { name: Artémis, img: img_artemis.png, desc: "{{ artemis_desc }}" }
  - { name: Arès, img: img_ares.png, desc: "{{ ares_desc }}" }
  - { name: Aphrodite, img: img_aphrodite.png, desc: "{{ aphrodite_desc }}" }
  - { name: Héphaïstos, img: img_hephaistos.png, desc: "{{ hephaistos_desc }}" }
  - { name: Hermès, img: img_hermes.png, desc: "{{ hermes_desc }}" }
  - { name: Dionysos, img: img_dionysos.png, desc: "{{ dionysos_desc }}" }

wordpress_users_gods:
  - { name: Zeus, password: "A8!zEus#2025" }
  - { name: Héra, password: "H3r@!2025" }
  - { name: Poséidon, password: "P0s3!d0n@2025" }
  - { name: Déméter, password: "D3m3t3r!2025" }
  - { name: Athéna, password: "Ath3n@!2025" }
  - { name: Apollon, password: "Ap0ll0n!2025" }
  - { name: Artémis, password: "Art3m!s@2025" }
  - { name: Arès, password: "Ar3s!2025" }
  - { name: Aphrodite, password: "Aphrod!t3@2025" }
  - { name: Héphaïstos, password: "H3ph@!st0s2025" }
  - { name: Hermès, password: "ilovegod" }
  - { name: Dionysos, password: "D!0nys0s@2025" }

