---
- import_playbook: windows_config.yml
  when: not windows_config_loaded | default(false)


- import_playbook: windows_coliseum.yml
- import_playbook: windows_rdp-winrm_access.yml
- import_playbook: windows_rdp-enfers.yml

- name: Afficher un résumé de la configuration
  hosts: pantheon-dc01
  tasks:
    - name: Résumé de la configuration
      debug:
        msg: |
          Configuration terminée :
          - Répertoire C:\coliseum créé
          - Tâche planifiée configurée pour Athena
          - Accès WinRM et RDP configurés pour Cronos et les dieux
          - Droits complets sur C:\coliseum pour Cronos 
