---
all:
  children:
    domain:
      children:
        extensions:
          hosts:
            pantheon-dc01:
              ansible_host: 192.168.56.11
              data_path: "{{ playbook_dir }}/../vars"
              playbook_path: "{{ playbook_dir }}"
            pantheon-enfers:
              ansible_host: 192.168.56.12
              data_path: "{{ playbook_dir }}/../vars"
              playbook_path: "{{ playbook_dir }}"
          vars:
            ansible_user: Administrator
            ansible_password: Pantheon@2024
            ansible_connection: winrm
            ansible_winrm_server_cert_validation: ignore
            ansible_winrm_transport: plaintext
            ansible_winrm_port: 5985


