---
all:
  children:
    domain:
      children:
        extensions:
          hosts:
            pantheon-dc01:
              ansible_host: 192.168.56.11
              data_path: "{{ playbook_dir }}/../vars"
              cert_signing_ca_shell_type: powershell
            pantheon-ca01:
              ansible_host: 192.168.56.12
              data_path: "{{ playbook_dir }}/../vars"
              cert_signing_ca_shell_type: powershell

  vars:
    ansible_user: 'Pantheon.god\Zeus'
    ansible_password: 'Th3und3rK1ng!2024'
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_transport: ntlm
    ansible_winrm_port: 5985 
